dist: trusty
language: java
jdk: oraclejdk8

env:
  - GRADLE_VERSION=5.6.2

before_install:
  - wget https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
  - unzip -qq gradle-$GRADLE_VERSION-bin.zip
  - export GRADLE_HOME=$PWD/gradle-$GRADLE_VERSION
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

script: gradle clean build

notifications:
  email: false
  